import './globals.css'
import { Inter,Raleway, Delius_Swash_Caps} from 'next/font/google'
import React from 'react'
import Header from '@/components/header'
import { QuerySearchWrapper } from '@/Context'

const inter = Inter({ subsets: ['latin'] })
const Delius = Delius_Swash_Caps({ subsets: ['latin'], weight: '400' });


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>
       <QuerySearchWrapper>
        {children}
       </QuerySearchWrapper>
      </body> */}
      <body className={Delius.className}>
      <QuerySearchWrapper>
        {children}
         </QuerySearchWrapper>
      </body>
    </html>
  )
}
